AllCops:
  Excludes:
    - lib/parser/lexer.rb
    - lib/parser/ruby18.rb
    - lib/parser/ruby19.rb
    - lib/parser/ruby20.rb
    - lib/parser/ruby21.rb

HashSyntax:
  Enabled: false

LineLength:
  Max: 120

MethodLength:
  Enabled: false

SymbolName:
  Enabled: false

IfUnlessModifier:
  Enabled: false

Lambda:
  Enabled: false
